### ISSUE TITLE
Great Net！What's vel in the codes?

### ISSUE THREAD

**Issue by 1121091694** [mouthful/ClofNet#1]
Nice ideas and code! I just have one question, What's vel in the codes?
I have tried not use vel, the training loss fluctuate wildly that means training failed.
Could you explain what it means and what it does. EGNN just need x and h, but ClofNet need x,h and vel, I want to learn how to use ClofNet without vel.
Thanks a lot.

**Comment by jackud233** [comment]
Hi!  You can check the conformation generation task's model, where we only use (x,h). Vel is only used i second order dynamics modeling, for example the Newtonian task.
